### ISSUE TITLE
Is there a way they can see the score when they decide to land on it?

### ISSUE THREAD

**Issue by nicholasphair** [kevinsullivan/moralpain_dev#10]
@vka7q

**Comment by nicholasphair** [comment]
Hi @vka7q, This bit of work (#18) updates the thermometer to permanently show the value. Does the fix resolve this issue? There are screenshots when you clink the link.

**Comment by vka7q** [comment]
I certainly like this better than it going away as they slide up the thermometer, but still like having their settled on score display right-side up off in a corner (right, preferably). But I can give that up.
