### ISSUE TITLE
prompt for next screen on scoring

### ISSUE THREAD

**Issue by nicholasphair** [kevinsullivan/moralpain_dev#11]
Is there a way for it to, once you score it, you get prompted to go to the next screen instead of finding the next button?

@vka7q

**Comment by nicholasphair** [comment]
Hi @vka7q, my concern with this is that it will become difficult for users to change their scores. If a button/message appears across the screen every time they land on a spot, then every change would be a dismissing of that screen, an update, and then the same message reappearing. Might be frustrating if someone is teetering between scores.

I don't want to dismiss your issue outright though. Is there something that led you to suggest this? Is the button hard to find?

**Comment by vka7q** [comment]
The button does feel hard to find, to me. I feel like people will rate it, and then be like, now what? And have to search for the button. What if their score goes up in the top right corner-and there is still a prompt after they land on a score? Or maybe a confirmation of the score, that then takes them to the next screen?

**Comment by nicholasphair** [comment]
Closing as OBE. UI should be clear now.
