### ISSUE TITLE
update question list

### ISSUE THREAD

**Issue by nicholasphair** [kevinsullivan/moralpain_dev#13]
The next screen will have be updated to reflect the more recent data with moral distress (MoD). Beth and I (with Lucia) will help to create new buckets for these.

Clustering by:
Individual
Unit
Organization

@vka7q

**Comment by nicholasphair** [comment]
Great, when you have the new groupings i'm happy to update.

**Comment by vka7q** [comment]
Got it. Will post them here when they've been decided.
