### ISSUE TITLE
force responses to questions

### ISSUE THREAD

**Issue by nicholasphair** [kevinsullivan/moralpain_dev#14]
I also think it should be a forced response-they have to select something, but also only if there scores are above a set limit that we should decide on. I think "3" feels right, that if they have a score of 4 or above, they HAVE to select some source. If they have a score of less than "3"-they don't have to select a source because they are not in distress.

@vka7q

**Comment by nicholasphair** [comment]
This makes sense but can we flush it out a bit more. Does something like
if score > 4:
  force 1 option from each category to be chosen
else
  no minimum option required.

Do you immediately make the user aware of this behavior with some sort of message?  Or do you do it only when they press the submit button?

**Comment by vka7q** [comment]
I would say:

if score >=4:
force an option from any category to be chosen
if score <=3, they don't advance to the next screen at all. 

I think having some breakdown of this, maybe at the bottom of the thermometer would be fine, but also don't want to encourage people to rate less than/= 3 so they don't have to do the app. (Maybe that won't be a concern and I'm catastrophizing). I like the idea more if it is only when the press the submit the button. But open to discussion.

**Comment by nicholasphair** [comment]
Replaced by #52 and #53. Can be closed.
