### ISSUE TITLE
additional options after survey complete

### ISSUE THREAD

**Issue by nicholasphair** [kevinsullivan/moralpain_dev#16]
“If you feel you need to have relief in the moment please click here.
If you feel you need to escalate this now to the MDCS, please click here."

@vka7q

**Comment by nicholasphair** [comment]
Do you envision this being a separate page after submitting the survey? Or options on the survey page?

**Comment by vka7q** [comment]
My instinct is saying it is a separate page, but I'm not sure if that is the correct way of conveying what I'm thinking. You know how when you hit submit, it says "Thank you, your response has been recorded"? I want that to be bigger and have all of this-so a whole screen that enforces the thank you, and provides those links. So, really, maybe it's making the "Thank you, your response has been recorded" little blurb go away altogether for favor of a separate page? Is that possible?

**Comment by nicholasphair** [comment]
Resolved with e62e27a6b5
