### ISSUE TITLE
Adding word "labels" to thermometer

### ISSUE THREAD

**Issue by vka7q** [kevinsullivan/moralpain_dev#26]
Hi Nick& co!
Like was mentioned in the meeting today, adding words to the thermometer-

"None" for 0
"Mild" for 1-3
"Uncomfortable" for 4-5
"Distressing" for 6-7
"Intense" for 8-9
"Worst Possible" for 10

**Comment by nicholasphair** [comment]
Hi @vka7q - Do you have a sketch or description on how exactly you want these words displayed? Just want to the the placement right.

**Comment by vka7q** [comment]
There's the thermometer that Lucia made (attached), but I'd adjust the placement a bit (see my edits). I'm also wondering if brackets might be useful, you know? Over words that list the numbers next to it. I made a crude drawing of it to give the gist. I'm not sure if including the numbers AND the brackets would be useful? If possible maybe just the brackets first, to see it clean?
[MDT paper version.pdf](https://github.com/kevinsullivan/moralpain_dev/files/7292881/MDT.paper.version.pdf)
[vkaeditsMDT.pdf](https://github.com/kevinsullivan/moralpain_dev/files/7292883/vkaeditsMDT.pdf)

**Comment by nicholasphair** [comment]
@vka7q Do we still want this?

**Comment by vka7q** [comment]
Hi @nicholasphair. It was something Lucia had invested in for her thermometer. I can check with her and Beth to see if it's something we should still work towards. It does not need to be prioritized.

**Comment by nicholasphair** [comment]
Thanks @vka7q. It would be great to ask them. Just trying to clear up some of this backlog of tickets.

**Comment by vka7q** [comment]
Hi @nicholasphair-I spoke with Lucia about this-the validated tool included the words for people who couldn't understand numbers-in the sense of, well, what does a "5" mean-is that kind of bad, or okay or kind of okay, you know? Her original tool also didn't include color, which I think helps somewhat with it. I'm curious how cluttered it would look/how difficult it would be to add the labels to be the "most clear"-but if it's quite a bit of work, I think the color scale has helped to add with some of the clarity around it. TL/DR: We don't have to add them, but if it's easy to do-maybe we should see what it looks like.
