### ISSUE TITLE
Localizing the App

### ISSUE THREAD

**Issue by nicholasphair** [kevinsullivan/moralpain_dev#36]
I know in android it is best to put your string constants into a resources file for localization:

https://developer.android.com/guide/topics/resources/localization

Is there a similar effort in flutter? I suspect so. 

We should figure out the equivalent best practice and migrate the constants we have as well as any stray magic to it.

**Comment by kevinsullivan** [comment]
Maybe define a "Constants" class in a constants.dart file, where the class serves to wrap a namespace around whatever constant definitions you want. Those could include complex styling choices for whatever.

**Comment by nicholasphair** [comment]
That's a good idea. We have the start of something like that here- https://github.com/kevinsullivan/moralpain_dev/blob/8bf3588/moralpain/lib/assets/constants.dart

Need to flush it out a bit more.

**Comment by nicholasphair** [comment]
Closing since we have a constants file and full localization support isnt on the roadmap.
