### ISSUE TITLE
Physically deployed Android app fails to connect to backend.

### ISSUE THREAD

**Issue by kevinsullivan** [kevinsullivan/moralpain_dev#38]
With the app deployed and running for the first time on my phone, I got through the thermometer and classification screens. It was only when I hit submit that I got a well delivered error message. As Nick said, at least the error message works! And that was absolutely true.

Bug: failure to connect to back end
Result: no data sent from phone to the report store; appropriate error  message displayed
Reproduce: Try install on your own Android and see what happens. Talk to Nick and Kevin for details about Kevin's setup.

**Comment by kevinsullivan** [comment]
Nick has confirmed problem after installing app on an older Android phone he had lying around.

**Comment by nicholasphair** [comment]
Resolved by d1117f3b
