### ISSUE TITLE
GUI Glitch: numeric temp tag tracks until cursor goes offscreen, and thereafter is lost

### ISSUE THREAD

**Issue by kevinsullivan** [kevinsullivan/moralpain_dev#4]
Replicate by running mouse pointer up and down to raise/lower thermometer temperature. It works unless/until the mouse pointer goes outside of the thermometer window. When the pointer comes back in, the numeric tag showing temperature no longer appears, making it hard to know exactly what temperature one is selecting. This look to be a little GUI programming bug of some kind.

**Comment by nicholasphair** [comment]
This seems like a flutter-web issue. I cannot recreate when emulating on an iphone. 

This label is also not something I am producing but the flutter libraries are producing. So fixing it is likely an upstream patch. 

So we have a few options...
1. Accept as is.
2. Look for an upstream fix
3. Display the value some other way.

**Comment by kevinsullivan** [comment]
Accept as is and document under known issues. We should add a new release
notes file in which we can document things like this.

**Comment by nicholasphair** [comment]
Closing,  resolved by #18
