### ISSUE TITLE
Web version posted on Teams site seems broken. Out of date?

### ISSUE THREAD

**Issue by kevinsullivan** [kevinsullivan/moralpain_dev#40]
I just tried it and basic interactions didn't work. I'm guessing it just hasn't been updated. We can either get rid of it there, or get things set up so that it stays updated as we push out new versions. Maybe getting rid of it for now is ok?

**Comment by nicholasphair** [comment]
Hmm, it looks like it is loading in Teams for me. The gh actions are actually setup to build the site so it should remain up to date

**Comment by nicholasphair** [comment]
Oops did not mean to close. Reopening

**Comment by kevinsullivan** [comment]
Thank you, Nick. Ok, that's good. I'll close this issue.
