### ISSUE TITLE
Changing the name of the App to "Moral Distress" over "Moral Pain"

### ISSUE THREAD

**Issue by vka7q** [kevinsullivan/moralpain_dev#50]
Feedback from nursing staff is to adjust the name to read "Moral Distress" over "Moral Pain"-I'm not too sure if it's a name based issue (was "Moral Distress" already taken?)-as an alternative can we do something like "MoD" as an abbreviation or something along those lines?

**Comment by nicholasphair** [comment]
Sure things - updates it.
