### ISSUE TITLE
Some interface thoughts about the app:

### ISSUE THREAD

**Issue by vka7q** [kevinsullivan/moralpain_dev#6]
Calling it “Survey,"-maybe changing that up a little bit:
	Moral Distress
What’s your temperature?

Getting rid of the lines on the thermometer?
Is purple an option?
Is there a way they can see the score when they decide to land on it?

Is there a way for it to, once you score it, you get prompted to go to the next screen instead of finding the next button?

While it is in all of the measurement tools, these first ones might do best with getting rid of the “Other" option altogether. (I think Nick, we had talked about the issues with this one)

The next screen will have be updated to reflect the more recent data with moral distress (MoD). Beth and I (with Lucia) will help to create new buckets for these. 

Clustering by:
Individual
Unit
Organization

I also think it should be a forced response-they have to select something, but also only if there scores are above a set limit that we should decide on. I think "3" feels right, that if they have a score of 4 or above, they HAVE to select some source. If they have a score of less than "3"-they don't have to select a source because they are not in distress.

Bigger “THANK YOU”-“Your response has been recorded and will be escalated if aggregate scores are high enough”

“If you feel you need to have relief in the moment please click here.
If you feel you need to escalate this now to the MDCS, please click here."

These are all just ideas for the next iteration.  I have talked them over with Beth.

**Comment by nicholasphair** [comment]
Hi @vka7q, thanks for the feedback. I can start making some of these changes. I will likely split this issue up into separate issues just to better track progress. I'll provide any updates in the appropriate issue.

**Comment by nicholasphair** [comment]
@kevinsullivan would it be possible to get the superpowers to close issues? Currently I can only comment on them.

**Comment by nicholasphair** [comment]
@vka7q I have taken this list and created separate issues for each item. We'll close this one in favor of those.

**Comment by vka7q** [comment]
@nicholasphair Thanks for separating them all out! I wasn't sure what would be the best format. I'll definitely keep that in mind with any other thoughts. Do let me know if I can help clarify or anything!

**Comment by nicholasphair** [comment]
Closing since these have been separated.
