### ISSUE TITLE
Security threat

### ISSUE THREAD

**Issue by kevinsullivan** [kevinsullivan/moralpain_dev#64]
Check for this vulnerability in our system and repair if necessary: https://github.com/advisories/GHSA-57j2-w4cx-62h2

**Comment by kevinsullivan** [comment]
Upgrade com.fasterxml.jackson.core:jackson-databind to fix [1 Dependabot alert](https://github.com/kevinsullivan/moralpain_dev/security/dependabot?q=is%3Aopen+package%3Acom.fasterxml.jackson.core%3Ajackson-databind+manifest%3Ainfrastructure%2Fsam%2FMoralPainFunctions%2Fpom.xml+has%3Apatch) in [infrastructure/sam/MoralPainFunctions/pom.xml](https://github.com/kevinsullivan/moralpain_dev/blob/-/infrastructure/sam/MoralPainFunctions/pom.xml)

Upgrade com.fasterxml.jackson.core:jackson-databind to version 2.12.6.1 or later. For example:

<dependency>
  <groupId>com.fasterxml.jackson.core</groupId>
  <artifactId>jackson-databind</artifactId>
  <version>[2.12.6.1,)</version>
</dependency>

**Comment by nicholasphair** [comment]
Resolved by 233ef8868364aac766dac907c04620b444f2c31b.
